### ISSUE TITLE
Adjust font and color styling for ASpace PUI

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#102]
A couple of adjustments need to be made to headers.

- [x] On the homepage, the fonts and colors should match the homepage of [Library Search](https://search.libraries.emory.edu/); the header is the wrong font and color (and possibly size?)

- [x] On the repository pages, the search bar styling should match the above

- [x] The [ASpace search page](https://emory-dev.lyrasistechnology.org/search?reset=true) looks like it is matching Library Search but should be double-checked

**Comment by maxdmayhew** [comment]
![Screenshot 2023-03-08 at 9.49.31 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/8fbff9e7-367d-47f1-99c3-d19130b2dc96)

![Screenshot 2023-03-08 at 9.51.52 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/bb3c1080-9945-46cd-94a9-a6999dad397b)

![Screenshot 2023-03-08 at 9.52.06 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/167f3517-9be6-41e6-b9ea-178b1f78b226)

Here are the three different pages mentioned. The last one (aspace saerch) for some reason is displayed as an h2 instead of an h3 like the other two. I can change it but I will need to override the existing template. 

![Screenshot 2023-03-08 at 9.51.58 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/4251d9d1-5252-4d19-a972-23c19d38e07c)

Above is a decent reason to keep the font larger on the search page (3rd image) since it the only thing really on the page. 

![image.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/70740718-3f16-4668-87a7-2ae76a89a4d2)

**Comment by maxdmayhew** [comment]
Will submit PR after approval or additional changes are made.

**Comment by erussey** [comment]
@maxdmayhew : this looks ok to me.  I don't want to override existing templates.  We'll catch some of this in the accessibility review that we'll do towards the end of the project.  If we find accessibility issues/inconsistencies in the core code, I can put in a series of tickets to have them fixed by the ASpace community devs.

**Comment by maxdmayhew** [comment]
The one issue I've noticed is appropriate use and nesting of headings. It might be best to just focus on our platform for now since we have a fairly customized implementation of this system.

https://accessibility.princeton.edu/how/content/headings
