### ISSUE TITLE
Develop custom footer and apply to all pages in public site

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#11]
Create an ArchivesSpace footer to match the [Aeon footer](https://github.com/emory-libraries/static-web-components/blob/main/footer.html) as closely as possible.  Please make the following changes:

- Change "About Aeon" to "About ArchivesSpace" and link to the new page developed in [ASpace ticket #63](https://app.zenhub.com/workspaces/archivesspace-63122393d517dc001c3ceb07/issues/emory-libraries/aspace/63).

- Please ensure that all styling, javascript, etc. is embedded within the html (for control/compatibility issues). 

- Remove the line starting with "Powered by Aeon..." 

- Add Version number and an update date (similar to LibrarySearch footer)

- Apply new footer to all pages within the public user application.

**Comment by CB987** [comment]
You may also want to make changes to the main index page, or the header and footer. Those overrides would go into the following places for the public side of your site:

archivesspace/plugins/local/public/views/welcome/show.html.erb
archivesspace/plugins/local/public/views/shared/_header.html.erb
archivesspace/plugins/local/public/views/shared/_footer.html.erb

**Comment by CB987** [comment]
@erussey Am I correct that Lyrasis said we can't do our version in the footer?

**Comment by CB987** [comment]
Please ensure that all styling, javascript, etc. is embedded within the html (for control/compatibility issues). -- Since we have a whole plugin for our static pages for AS, unlike aeon, and the styling is being handled very differently, with sass, and the app itself is rails, I did not follow this directive, but kept pretty close to the search footer style and setup.

**Comment by CB987** [comment]
![Screen Shot 2023-02-08 at 10.12.00 AM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/63edc9f1-6c6b-4174-b117-f192859f9f42)
First pass is done, I need to do some refactoring and Elizabeth asked me to see what I can do about getting AS version info from their footer.

**Comment by CB987** [comment]
![Screen Shot 2023-02-09 at 7.26.37 AM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/27b918a7-5e12-4b5a-b771-0c0a3741b1f1)
PR10 submitted. 
I used the AS variable for the version that they were using in their footer, which as of this screenshot was pulling what branch my local archivesspace repo was on, which is why it says "Version master".

**Comment by CB987** [comment]
This ended up being a greater learning curve and took more time that I was expecting for the customizations, so I increased the points estimation to better reflect the time I put in.

**Comment by erussey** [comment]
Can we put the version number (i.e. "version master") above the copyright statement so it matches Library Search?

**Comment by erussey** [comment]
Can we put the version number (i.e. "version master") above the copyright statement so it matches Library Search?

**Comment by CB987** [comment]
![Screen Shot 2023-02-10 at 10.42.49 AM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/52d570d7-3764-44d5-a5f4-557772e1c7d0)
done!

**Comment by CB987** [comment]
PR#14

**Comment by CB987** [comment]
PR#14
