### ISSUE TITLE
Adjust ASpace header in production environment

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#124]
In the deployment to production, the ASpace header isn't quite right.  It's currently showing like this:
![Screen Shot 2023-04-07 at 8.24.07 AM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/92d4e83d-104b-4cd7-8988-7f56a113dc96).

Per work done in #90, it should look like this: https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/685f0964-2c7e-492e-8a7a-0fdff9b54e9b

**Comment by CB987** [comment]
Based on the dev tools, the issue is with the header background color, which is i think coming from their “theme.css” file again. we ran into this earlier in the project. I’ve posted a message in basecamp.
per this message from before https://3.basecamp.com/3410311/buckets/29543127/messages/5844728562
i think it’s the same issue so hopefully it will be as easy for them to resolve.

**Comment by CB987** [comment]
Looks like Lyrasis had to exclude a plugin they generate, in order to stop the theme.css
