### ISSUE TITLE
Operating Level Agreement: ArchivesSpace

### ISSUE THREAD

**Issue by tmill29** [emory-libraries/aspace#132]
- [x] Finalization of the [AEON OLA](https://emory.sharepoint.com/:w:/r/sites/EULLTDS/Shared%20Documents/LTDS%20Technology%20Agreements/Drafts/OLA-Aeon/OLA-Aeon-Draft-2022-for-Approval.docx?d=w16f81e33de1f4718b35aca58f3de5f6e&csf=1&web=1&e=4kGe05)- This is pending the review with the Service Owners

- [x] Initial creation of the [ArchivesSpace OLA draft](https://emory.sharepoint.com/:w:/r/sites/EULLTDS/Shared%20Documents/LTDS%20Technology%20Agreements/Drafts/OLA-ArchivesSpace/OLA-ArchivesSpace-Draft-2023-for-Approval.docx?d=w74ff3f47784b47b498f7a644f9c97b87&csf=1&web=1&e=5TPeHc)

- [x] Acceptance of [Service Criticality Tiers](https://emory.sharepoint.com/:w:/r/sites/EULLTDS/_layouts/15/Doc.aspx?sourcedoc=%7B4A689C21-7071-46D5-A462-72598E71C6CB%7D&file=DRAFT%20-%20Service%20Criticality%20Tiers.docx&action=default&mobileredirect=true&cid=3dd0c883-7e4b-495d-9298-df63cc2099d3)
- [x] Acceptance of [Aeon Support Tiers](https://emory.sharepoint.com/:w:/r/sites/EmoryUniversityLibraries/_layouts/15/Doc.aspx?sourcedoc=%7BF59535C5-F7AD-494C-8CDB-4040CE72D1DF%7D&file=Aeon%20support%20tiers.docx&nav=eyJjIjo2MzMyNDE4OTZ9&action=default&mobileredirect=true&cid=bd2ee5bb-f8f9-4763-ae75-7c2465e5f377)
- [x] Acceptance of [ServiceNow Ticket Norms](https://emory-my.sharepoint.com/:w:/r/personal/cbrittl_emory_edu/_layouts/15/Doc.aspx?sourcedoc=%7BC37F45FB-F864-471F-8B1C-37B88BCD3190%7D&file=Service%20Now%20Ticket%20Norms.docx&action=default&mobileredirect=true&DefaultItemOpen=1&cid=fa78fba3-4e11-4a3f-9355-e9604e569149)
- [x] Determine the OLA permissions in viewing documentation

**Comment by AGCooper** [comment]
Draft https://emory.sharepoint.com/:w:/r/sites/EULLTDS/_layouts/15/Doc.aspx?sourcedoc=%7B74FF3F47-784B-47B4-98F7-A644F9C97B87%7D&file=OLA-ArchivesSpace-Draft-2023-for-Approval.docx&action=default&mobileredirect=true

**Comment by tmill29** [comment]
Adding to blocked due to the dependency of the [Aeon OLA](https://emory.sharepoint.com/:w:/r/sites/EULLTDS/Shared%20Documents/LTDS%20Technology%20Agreements/Drafts/OLA-Aeon/OLA-Aeon-Draft-2022-for-Approval.docx?d=w16f81e33de1f4718b35aca58f3de5f6e&csf=1&web=1&e=4kGe05) and [OLA template](https://emory.sharepoint.com/:w:/r/sites/EULLTDS/Shared%20Documents/LTDS%20Technology%20Agreements/OLA-TEMPLATE-2023.docx?d=wf676b31ff87d4865877f48990ce454bd&csf=1&web=1&e=OaZQIY).

**Comment by libdgg** [comment]
Alex, Elizabeth, Cari and I are meeting Monday 5/22. Draft agenda below.

We need to get closure for the 2 associated documents below before we can complete the [Aeon OLA](https://emory.sharepoint.com/:w:/r/sites/EULLTDS/Shared%20Documents/LTDS%20Technology%20Agreements/Drafts/OLA-Aeon/OLA-Aeon-Draft-2022-for-Approval.docx?d=w16f81e33de1f4718b35aca58f3de5f6e&csf=1&web=1&e=Pw1CHx) work.

[Support Tiers](https://emory.sharepoint.com/:w:/r/sites/EmoryUniversityLibraries/Shared%20Documents/Project%20Management%20Office/EUL%20Projects/01%20Active%20Project/Aeon%20Upgrade/02%20Planning%20and%20Execution/Aeon%20support%20tiers.docx?d=wf59535c5f7ad494c8cdb4040ce72d1df&csf=1&web=1&e=hBox27)

- Everyone needs to review the following ServiceNow article which explains response/resolution times for assignment groups.

- https://emory.service-now.com/nav_to.do?uri=%2Fkb_view.do%3Fsysparm_article%3DKB04113
-- Core Systems is Platinum
-- Tech Support Training is Platinum
-- Software Engineering is Gold
- We then need to reference (or indicate) those in the Support Tiers document
- Then Cari and Doug need to review application criticality to ensure that is being viewed through those support tiers accurately - specifically for Aeon in this case
- I added a signature block for approval on the document

[Ticket Norms](https://emory-my.sharepoint.com/:w:/r/personal/cbrittl_emory_edu/Documents/Service%20Now%20Ticket%20Norms.docx?d=wc37f45fbf864471f8b1c37b88bcd3190&csf=1&web=1&e=wpW9ig)
- Review the comment on re-opening ticket process for resolution
- Review the service level (Platinum or Gold) times per servicenow assignment groups and reference (or indicate those) in the document
- I added a signature block for approval on the document

The Aeon OLA is otherwise ready once we get closure on the above bullets.
Once that is done it should unblock the remaining work for the ASpace OLA.

**Comment by libdgg** [comment]
@erussey @lovinscari @AGCooper and @libdgg 
ACTION:

- CL and DG confirm with RM that [Service Criticality Tiers](https://emory.sharepoint.com/:w:/r/sites/EULLTDS/_layouts/15/Doc.aspx?sourcedoc=%7B4A689C21-7071-46D5-A462-72598E71C6CB%7D&file=DRAFT%20-%20Service%20Criticality%20Tiers.docx&action=default&mobileredirect=true&cid=826f07f9-f492-4bf4-abb5-cb4a01aa2638) is based on P1 (P1-P5 will be described within [Ticket Norms](https://emory-my.sharepoint.com/:w:/r/personal/cbrittl_emory_edu/_layouts/15/Doc.aspx?sourcedoc=%7BC37F45FB-F864-471F-8B1C-37B88BCD3190%7D&file=Service%20Now%20Ticket%20Norms.docx&action=default&mobileredirect=true) and/or OLAs) and that Aeon is group 3 or can it be moved group 2 like ASpace.

- ER and AC will draft P1-P5 and update the [OLA](https://emory.sharepoint.com/:w:/r/sites/EULLTDS/_layouts/15/Doc.aspx?sourcedoc=%7B16F81E33-DE1F-4718-B35A-CA58F3DE5F6E%7D&file=OLA-Aeon-Draft-2022-for-Approval.docx&nav=eyJjIjoxMTg3MTc1NzEwfQ&action=default&mobileredirect=true&cid=eabe2488-1ccc-4f16-b032-570725a68a44) and Ticket Norms documents and edit signature block as needed. See if they can put P1-P5 in the Norms as an alternative to outlining them in the OLA. Final edits to the [Aeon Support Tiers document](https://emory.sharepoint.com/:w:/r/sites/EmoryUniversityLibraries/_layouts/15/Doc.aspx?sourcedoc=%7BF59535C5-F7AD-494C-8CDB-4040CE72D1DF%7D&file=Aeon%20support%20tiers.docx&action=default&mobileredirect=true).

NOTE: The work above will inform updates to the OLA template ServiceNow CI etc.

**Comment by tmill29** [comment]
Alex and Elizabeth will meet this Thursday.

**Comment by lovinscari** [comment]
@erussey and @lovinscari to meet 6/22/23 to review the comments and status of the Aeon OLA. A meeting to confirm Aeon support tiers and operational workflows is scheduled for 6/26/23 with everyone involved in the processes. Notes and comments from that meeting will be noted as information needed for the ArchivesSpace OLA.

**Comment by lovinscari** [comment]
The individuals responsible for supporting Aeon and ArchivesSpace met on 6/26/23 to review the Support Model Tiers document, draft OLA, Service Criticality Tiers and ServiceNow ticket norms document. The Support Model Tiers document was reviewed in its entirety, which I will incorporate comments, edit the document (cleanup) and send to the individuals listed for their approval. Another meeting will be scheduled for the week of 7/24/23 to hopefully finalize the remaining documents and incorporate the work from Aeon support documents into the ArchivesSpace support documents. Links to documents and meeting notes to be added by the end of this week.

**Comment by tmill29** [comment]
Meeting will be held July 27th to discuss Aeon OLA.

**Comment by erussey** [comment]
OLAs being sent out for final signature week of October 23.
