### ISSUE TITLE
Revise the help and contacts page.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#138]
- [x] Add a navigation box for navigating the page structure.  The headings for each section can be used for this.

- [x] Change the header for "ArchivesSpace" to "About ArchivesSpace"

- [x] Change the text under "How to request materials" to: "For manuscripts and archives collections, use the Aeon request button next to the material you would like to request.  Restricted materials cannot be requested for use. For printed materials found via Library Search, use the request button in the catalog record to access the request system. Once you have initiated a request you will be prompted to either create a Special Collections Request account or login to and existing one."

- [x] Add a "Contact Us" header after "Copying/Using  and..."  The text should read: "To speak with an archivist or for additional assistance, please either visit Ask A Librarian or use the contact information on the repository page."
Links for the above:

- Ask a librarian: https://libraries.emory.edu/contact/ask-librarian

- Repository page: https://archives.libraries.emory.edu/repositories

Note that internal linking on this page will point to prod, not test so we don't have to maintain two sets of pages.

**Comment by maxdmayhew** [comment]
Two additional comments/questions from this ticket:

How should the navigation be set up? Should it be on the left hand side with a 1/4 to 3/4th of the page being split? Similar to the image I provided? Would you be interested in displaying it as an accordion instead? (which could look sort of like this: https://urec.charlotte.edu/aquatics/safety-courses) it could keep things more “above the fold” so users don’t have to scroll to find anything.

![image.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/03aeebdf-f05e-47b8-b5eb-66d86149d99c)

I’m not sure if this is helpful but I wasn’t aware at first that I needed to click on a repository in order to find contact information. I was looking for it on the actual /repo page itself.

**Comment by erussey** [comment]
@maxdmayhew : fair enough on the repository page text.  Maybe this is better (also happy to hear suggestions): "To speak with an archivist or for additional assistance, please either visit Ask A Librarian or select a repository to see contact information for Emory's special collections repositories."  (link 'select a repository')

**Comment by maxdmayhew** [comment]
1: ![Screenshot 2023-04-28 at 1.34.05 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/a59a1516-bc40-4292-8938-6ee57708ce67)

2: ![Screenshot 2023-04-28 at 1.34.19 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/ce097ea4-0d75-4596-b4fa-37936afbc7e3)

3: ![Screenshot 2023-04-28 at 1.35.00 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/6eb404a0-3112-4c23-955c-229eeeb76d52)

4: ![Screenshot 2023-04-28 at 1.34.38 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/eea83d2d-060d-4f5a-9964-b9b2b1fd6a13)

What do you think @erussey? I can do any of these styles. And I could flip the layout if you think it would look better since generally menus are often times on the left side.

**Comment by maxdmayhew** [comment]
And the updated text is much more clear to me! (and hopefully new users as well)

**Comment by erussey** [comment]
@maxdmayhew : we prefer #3.  Navigation can stay on the right since that's where navigation is for other pages in ASpace.  I will have one more text change for you on this page after we get the page in #140 started to cross reference the two.

**Comment by maxdmayhew** [comment]
![Screenshot 2023-04-28 at 5.45.42 PM.png](https://images.zenhubusercontent.com/633dacae52c9e27764e5849b/a3c39b84-190b-48df-a67d-9ef46c6edefb)

submitting PR
