### ISSUE TITLE
Update ArchivesSpace to the latest version (3.4.1)

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#171]
Release notes: https://github.com/archivesspace/archivesspace/releases

We are already on 3.3.1.

**Comment by abelemlih** [comment]
@erussey @rotated8 I upgraded ArchivesSpace on my local to 3.4.1 and built the application, and the public and Admin interfaces are both functional and stable, and all Emory customizations are displayed correctly.

In terms of upgrading ArchivesSpace Test and Prod instances to 3.4.1, there is not much our team can do, except for asking the ArchivesSpace team, since we do not have direct access to the applications. To move forward, we will need to ask the Aspace team to upgrade the version on the instances.

**Comment by erussey** [comment]
@abelemlih @rotated8 : we may want to hold off upgrading until 3.5.0.  There was a significant bug reported a few days ago: https://archivesspace.atlassian.net/browse/ANW-1829. Should we move this into blocked?
