### ISSUE TITLE
Update Aeon webpages to include 6.0 changes

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#178]
Release notes: https://support.atlas-sys.com/hc/en-us/articles/26772719857043-Aeon-6-0-Release-Notes

New webpages: https://support.atlas-sys.com/hc/en-us/articles/360012610813-Aeon-Downloads

Please note that our webpages have customizations that will need to be retained.  Changes will need to be made on both Shibboleth-based and non-Shibboleth-based webpages (which are different).  

Workflow procedures for Aeon webpage updates: https://emorylib.atlassian.net/wiki/spaces/EA/pages/20774956/Editing+Aeon+webpages+in+Github

**Comment by CB987** [comment]
spent some time re-familiarizing myself with the system.
Contacted Aeon support to request credentials to be able to download files.
Communicated with Katie Gillespie for clarification on how to tell what has been customized and what the best workflow is for updating files with the expectation that we have a lot of customizations. She said that if a file hasn't been touched via github in 2 years then it probably *hasn't* been customized and can safely be replaced. The registration forms, request forms, and appointment pages have significant customizations. 
Emory is currently on server version 5.2.4 in production. The sandbox was updated to 6.0 08/13/2024.
Downloaded the default and feature files for 6.0. There are a significant number of files. As far as i can tell, I just need to go through the files individually, checking them against github and updating our repo as seems appropriate. Working through the default files first and then will do the feature files.

**Comment by CB987** [comment]
recording what customizations i come across as i go (as best i can tell):

**we do not include**
-  css/print.css (the file is there but it is empty) or css/print.min.css
-  the templates/captcha folder? it is missing from our repo, looks like it came in with 5.2.4 so. not sure if we aren't using it or it just hasn't been added yet. --will ask ERR, skipping for now.

**files that have our customizations**
- js/custom.js
- /templates/pickupinfo is ours
-  templates/DataRow_DefaultAppointment.html **is** in our repo but not in the 5.2 or 6.0 default files (it could be in feature files)
-  assuming that the block with "Library Pickup Info" is our customization that connects to the pickupinfo folder noted above, so keeping it in the templates/DataRow_DefaultRequest.html file

**katie is working on**
- js/ArchivalRequest.js
- js/atlasUtility.js
- js/billingAccountsOptionHandler.js
- Aeon/js/billingContextOptionHandler.js
- js/datepicker.js -- looks like incoming changes is just formatting?

**Comment by CB987** [comment]
future work is to amend the files like we have done for hyrax which says if the individual file has been overridden and which lines or range of lines. this will make the future process a lot clearer.

**Comment by erussey** [comment]
@CB987 : We do not use captcha at this point so that file can be ignored.  I'm not entirely such what "Library pickup info means" since we do not circulate information.  I think that it might be a customization that does not give users the option to pick the library where they want to see the material.  Again, Katie would be the one to ask about this.

**Comment by CB987** [comment]
👍🏻 re captcha
the text of the pickup info files looks like
`  Your research visit will take place at the Historical Collections of the Emory's Woodruff Health Sciences Center Library. ...`
but either way i don't think it will hurt it to keep it.

**Comment by erussey** [comment]
@CB987 : the text above is absolutely needed.  We have some custom text that displays to the end user to let them know the details of their visit.  I'm not sure how that plugs into the other files, but I assume it does somehow?

**Comment by CB987** [comment]
continued **customizations**, top level files after the templates folder:
- basically all of the html pages have customizations to some extent because we use the terminology "Request System" instead of "Aeon" , and we have the footer outside of the `<div class="container">` instead of inside it.
- AboutAeon.html
- aeon.xslt has a lot of changes,, not touching it.
- Blocked.html
- ChangePassword.html
- ChangeUserInformation.html -- i don't know what is our customizations and what is them updating so i'm leaving it all.
- CreditCardPayment.html , leaving it
- EADRequest.html leaving body
- ExpiredUsers.html - leaving it
- FAQ.html - leaving it
- FirstTime.html - leaving it
- include_footer.html (obviously)
- include_header.html
- include_nav.html - left it as is

**katie in progress**
- ArchivalRequest.html -- I updated the scripts in the header only, not any of the body
- DefaultRequest.html - idk what's ours vs theirs so leaving it all
- include_photodup_toggle_enabled.html - leaving it
- include_photoduplication_archival_request.html
- include_photoduplication.html
- 

**questions** (please double check whether these should have/ not changed
- include_scheduleddate_review_toggle.html - i left it as it was.
- include_scheduled_date.html --we don't have this file, but it's in the 6.0 files, so i added it.
- log4d.props - debugger logging?

**Comment by CB987** [comment]
@erussey re the pickupinfo file -- ok good, that's what i thought. i believe i saw where it is called, so that makes sense.  i am making progress working through the files.

**Comment by CB987** [comment]
**customizations**
- NewUserRegistration.html
- ViewOrderApprovals.html -- updated lines 35-36 but left the rest
- include_nav.html -- left it as is

**katie in progress**
- PhotoduplicationRequest.html -- leaving it
- include_photodup_toggle_disabled.html

**questions**
- ViewOrderEstimates.html -- lines 18-19 changes verbiage slightly. we could keep the new formatting and leave the old text?
- web.config -- file in 6.0 default files only shows up in the Logon/ folder in ours, and is significantly different. leaving ours.
- appointments.js -- i don't think it's customized so i'm pushing through the updates but jic
- EADRequest.html also in the feature files, leaving ours

**Comment by CB987** [comment]
Here's my PR
https://github.com/AtlasSystems/hosting-aeon-emorysb/pull/8
This has all the files (except ones noted above) from the 6.0 Default files and 6.0 Feature files updated and maintaining our customizations to the four directories in the repo. 
I emailed Katie and copied Elizabeth for next steps.
