### ISSUE TITLE
Implement and configure banner plug-in

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#20]
Add plug-in for banner announcements: https://github.com/archivesspace-plugins/sandbox_header 

This banner, most of the time, should not be on the site and should only be implemented in case of scheduled downtime or other urgent announcements as determined by the product owner, Core Systems, or LTDS leadership.  Note that there is default text in the plug-in that will need to be changed for Emory use.

**Comment by abelemlih** [comment]
@rotated8 @erussey adding this plugin to our ArchivesSpace space is simple. We just need to create our own copy and customize the text and where the notice is displayed. By default, the notice is only displayed on the admin side.

This is a screenshot of what the notice looks like:

![Screenshot 2023-01-25 at 12-25-32 ArchivesSpace Home.png](https://images.zenhubusercontent.com/6151f04e7e6954612001d8f9/5288009b-9915-4074-a6d5-f25b030fae34)

Alternatively, we could avoid using one extra repository to store the notice related functionality, and add it to our main plugin. The implementation of the notice is fairly simple, so adding our own implementation should be straightforward.

In #21, I will add more details regarding the ability to configure the notice text from the admin side instead of having to redeploy.

**Comment by erussey** [comment]
@abelemlih : Can we also apply this to the public interface side?  That is where the need is most critical, though as we've said before, we'd like to be able to apply to public, admin, or both.

**Comment by abelemlih** [comment]
@erussey yes, we can apply it to both the public and admin interfaces

**Comment by abelemlih** [comment]
@erussey I have a PR ready for review, and this is what the banners will look like in both the admin and public interfaces:

![Screenshot 2023-01-27 at 15-46-54 ArchivesSpace Home.png](https://images.zenhubusercontent.com/6151f04e7e6954612001d8f9/1839641e-d589-4cef-a088-e518d083b8b4)

![Screenshot 2023-01-27 at 15-46-18 ArchivesSpace Public Interface ArchivesSpace Public Interface.png](https://images.zenhubusercontent.com/6151f04e7e6954612001d8f9/a11f11fc-86b0-4511-bb6b-c9008c74f46e)

Let me know if you have any feedback/questions!

**Comment by maxdmayhew** [comment]
Woops! My bad!

**Comment by abelemlih** [comment]
@erussey This ticket is ready for QA. The screenshots above display how the banner is set up for both the admin and public interfaces. Let me know if you have any questions/feedback!

**Comment by erussey** [comment]
This looks good to me.
