### ISSUE TITLE
Archive EFA production SVN data

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#39]
- [x] Discuss where data should live
- [x] Move the data
- [x] Document counts in this ticket
- [ ] Move to Review for Product Owner to do final testing

**Comment by tmill29** [comment]
Work on this ticket can begin on July 26th or after, once Elizabeth returns from vacation.

**Comment by erussey** [comment]
Decision to use Github@Emory for the archived SVN data (https://github.service.emory.edu/cbrittl/efa-svn-data).  We would like to archive it for 3 years, then delete the repository.

**Comment by kbowaterskelly** [comment]
After reviewing what I believe to be the subversion instance in question @ https://svn.library.emory.edu/websvn/ I have some issues/questions.
1. Is this the correct SVN instance? I am not aware of any others that are referenced in our documentation.
2. There are around 40 repos here. @erussey to identify which ones we need. It does not seem feasible at this point to turn the entire SVN instance off unless we are prepared to potentially upset people by doing so.
3. The repo named "findingaids" appears to not have been edited since 2012. This suggests that perhaps I am looking in the wrong place, or there are additional repos that are pertinent here.
4. I will need to be granted appropriate user permissions to manipulate data in this SVN instance. Who administers this normally? Elizabeth?

Once these items are resolved, we can proceed with migration of our data to the private Github and possibly disable the SVN. That migration is supported until January of 2024. @rotated8 is waiting to proceed with other work so that I can have a fresh/clean Git instance to work with for the migration, so these items are currently a blocker for that.

**Comment by erussey** [comment]
@kbowaterskelly : here's the list of svn based repos associated with EFA:
These need to be archived and then deleted:

- https://svn.library.emory.edu/svn/ead-marbl

- https://svn.library.emory.edu/svn/ead-health

- https://svn.library.emory.edu/svn/ead-oxford

- https://svn.library.emory.edu/svn/ead-law

- https://svn.library.emory.edu/svn/ead-eua

- https://svn.library.emory.edu/svn/ead-pitts

These are from our test environment and can just be deleted:

- https://svn.library.emory.edu/svn/dev_ead-marbl

- https://svn.library.emory.edu/svn/dev_ead-pitts

- https://svn.library.emory.edu/svn/dev_ead-eua

- https://svn.library.emory.edu/svn/dev_ead-health

- https://svn.library.emory.edu/svn/dev_ead-law

- https://svn.library.emory.edu/svn/dev_ead-oxford

**Comment by erussey** [comment]
I would appreciate a link to the websvn server (I have lost the url) so I can see all the repositories there.  Just want to double check I didn't miss one.

Not sure what to say about permissions. I grant permissions to the above repos through a django client associated with the EFA web UI.  I do not have access to that now that we turned off access to the web EFA.  James Bias might be a god resource here since he set all of this up for us a few years ago following a server migration.

**Comment by kbowaterskelly** [comment]
1.  There is a link to the HTTP interface of the SVN in ticket #40.
  2.  We can put anything back online temporarily because the only thing we've done is redirect traffic away from the old finding aids and not truly disabled anything.

We'll discuss further in 15

________________________________
From: Elizabeth Russey Roke ***@***.***>
Sent: Tuesday, August 8, 2023 6:01 AM
To: emory-libraries/aspace ***@***.***>
Cc: Bowater-Skelly, Kaeln Joseph ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [emory-libraries/aspace] Archive EFA production SVN data (Issue #39)


I would appreciate a link to the websvn server (I have lost the url) so I can see all the repositories there. Just want to double check I didn't miss one.

Not sure what to say about permissions. I grant permissions to the above repos through a django client associated with the EFA web UI. I do not have access to that now that we turned off access to the web EFA.

**Comment by libdgg** [comment]
Per the email thread "Re: ArchivesSpace OIT Assistance" Doug has scheduled a meeting with Torri, Elizabeth, Kaeln, Cari, Beth and Alex to go over the topic and plan next steps.

**Comment by kbowaterskelly** [comment]
I have finally been able to migrate one of the repos to Github. It needs to be QA'd. The repo in question is https://svn.library.emory.edu/svn/ead-marbl
1. The changes are tracked by NetID, which to me seems fine, but may not be.
2. The change tracking appears good to me, but bears inspecting on the SVN side.
3. The directory structure is wonky. We need to decide on a schema for storing these repos, either by having multiple git repos, or by separating "Subversion Repos" into "Git Branches" in the same Git Repo.
If the content appears accessible and valid to the stakeholders and this is sufficient for our purposes, we should be able to move forward.

**Comment by erussey** [comment]
@kbowaterskelly : Took a look at the repository loaded into GitHub.  Tracking by netID is fine.  Change tracking also looks good and the history of each file is intact (and easy to follow in github!).  I would look to others (perhaps in today's meeting) to talk about how to structure the repositories as a whole.  I'd prefer to be able to look at each repository as it exists for Rose in the repo right now.  What I will need/want to do is to be able to click into a repository and see all the changes that happened to a single file over time.

**Comment by rotated8** [comment]
I created a [repo for the db dumps](https://github.service.emory.edu/cbrittl/efa-db-dumps) and added the files. @kbowaterskelly and @erussey have been added as collaborators.

For the SVN repos, each will get a separate git repo, which will be private and have @erussey added as a collaborator.

**Comment by erussey** [comment]
@kbowaterskelly : To be more specific on the item counts above, QA is to get a count of the files on SNV and a count of the files that are in Github for each repository.  Then post those numbers in a comment on this ticket.

**Comment by kbowaterskelly** [comment]
ead-eua: 1190 revisions, 5677 files locally before cleaning
after cleaning, 5902 files
local git repo - 1190 revisions, 5946 tracked files
online repo - 1190 revisions

ead-oxford 493/505 no change after clean
243 commits


ead-health: 877 files, 855 tracked, same after cleaning

kbowate@wml-kbowate-ltp ead-law % ls -R | wc
      57      57     582
kbowate@wml-kbowate-ltp ead-law % git ls-files | wc                                                        
      54      55     554
230 commits on git

ead-marbl before
kbowate@wml-kbowate-ltp ead-marbl % git ls-files | wc                                                        
    1377    1377   21638
kbowate@wml-kbowate-ltp ead-marbl % ls -R | wc                                                              
    1383    1381   21572
after
kbowate@wml-kbowate-ltp ead-marbl % ls -R | wc                                                                   
    1383    1381   21572
kbowate@wml-kbowate-ltp ead-marbl % git ls-files | wc                                                            
    1377    1377   21638
9085 commits

ead-oxford 493/505, no change, 243 commits

kbowate@wml-kbowate-ltp ead-pitts % git ls-files | wc
     531     531    6767
kbowate@wml-kbowate-ltp ead-pitts % ls -r | wc       
     531     531    6754
no change
1783 commits

**Comment by kbowaterskelly** [comment]
Source material: Mostly https://www.atlassian.com/git/tutorials/migrating-overview
Note that this is preparing migration to Bitbucket, which we are not using, and not all of the steps apply to us.
Packages required: brew (for Mac), git, svn, git-svn, java. These may have sub dependencies.

Download the migration script from Atlassian: https://bitbucket.org/atlassian/svn-migration-scripts/downloads/svn-migration-scripts.jar
Run the script to check that your dependencies are in order 
java -jar ~/svn-migration-scripts.jar verify

Create a case sensitive volume named Subversion, GitMigration, or what have you
It is possible to use this script to create a case sensitive partition if on Mac, but I preferred to use the disk utility.
Example syntax: 
java -jar ~/svn-migration-scripts.jar create-disk-image 5 GitMigration
This would create a 5GB partition named GitMigration

Extracting author information: We skip this step because the NetID is sufficient for our purposes. It also didn't work for me when I tried, so if it's something you need, it will require troubleshooting.

Change directories to your new volume

To pull down copies of the SVN repo:
We are assuming a standard layout (Trunk, branches, tags)
git svn clone --stdlayout https://svn.library.emory.edu/example example
Run this at least twice to make sure no files were missed, you should get some blank output the second time

If using a non standard  layout see the tutorial

At this point you can use git to inspect the new directory that was created, eg. git branch -r or to get a filecount of tracked files, git ls-files | wc, etc

Now we're going to clean up the repo, enter its root directory and run the following. We can safely force this even though it is a destructive operation because this is only acting on our local copy of the repo.
java -Dfile.encoding=utf-8 -jar ~/svn-migration-scripts.jar clean-git --force

This should now be a clean converted copy of the SVN repo

We are skipping synchronization because these are read only archived repos

Create your new private Github repo and make sure you have your SSH key
Note: It is probably possible to kludge this so that we could have multiple SVN repos in one github repo in different branches, but the toolchain does not explicitly support this so I decided not to.

Run from the root of the repo:
git remote add origin git@github.service.emory.edu:yourusername/example.git  
git branch -M main
git push -u origin main

Provide authentication as needed.
You should now have a working converted copy on Emory's github. Poke around and make sure everything looks good.

A recommended QA process is to compare the repo on the subversion server and the one on the github server. Commits and updates or whatever they're called on SVN should match exactly. https://svn.library.emory.edu/svn/
Elizabeth would need to provide you access to the SVN, but presumably you already have this by this point!
Note: This operation will only be supported til January of 2024. If we need to convert other SVN repos we should begin well before then.

**Comment by erussey** [comment]
@kbowaterskelly : this looks good.  And thanks for the instructions above.
