### ISSUE TITLE
Revise controlled value lists

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#54]
Revise the controlled value lists in ArchivesSpace based on the final data load.  Depending on the scope of the problems, this may be a post-implementation (non-project) task.

**Comment by erussey** [comment]
This needs to wait until the final data load is complete.  Then we can set those in prod and ask for a data refresh in test once they are set to avoid having to create and configure these twice.

**Comment by libdgg** [comment]
@erussey @tmill29 Checking on our process.  Is it assumed that this ticket is in the current sprint and blocked and there is an effort to unblock it during the sprint? Or, since this has no sprint or estimate assigned, I assume it is a future item per the comment 6 days ago and we just know it will be blocked until some point in the future?

**Comment by tmill29** [comment]
@libdgg please see @erussey comment above. It was also recommended by @rotated8 to add this ticket to Blocked due to the fact that is blocked because we are waiting for the final data load.

**Comment by erussey** [comment]
I have configured events and local access restriction types.  Leaving the rest alone with the intent to revisit as we learn to use the system.

I would like to schedule a refresh of test to sync these changes there.

**Comment by tmill29** [comment]
Elizabeth will send an email to Blake on Monday the 7th regarding this deployment

**Comment by erussey** [comment]
Deployed as of 8/9/2023
