### ISSUE TITLE
Configure admin/staff header

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#75]
- Add the Emory libraries logo used on the homepage of the ArchivesSpace public user interface (see [ticket #12](https://app.zenhub.com/workspaces/archivesspace-63122393d517dc001c3ceb07/issues/gh/emory-libraries/aspace/12)). Logo should be white and on the left.

- Configure the header to fill the rest of the space with an Emory blue banner.

-Maintain the default menus and buttons on the right.

**Comment by CB987** [comment]
Started on this but nothing to see, mostly setting up files and haven't pushed anything yet.

**Comment by erussey** [comment]
Please @CB987 check the spacing of how the page displays...for some reason everything is tabbed in a bit?![Screen Shot 2023-02-15 at 2.01.42 PM.png](https://images.zenhubusercontent.com/62ff941ccf40d827200a9edf/3cb5dcbe-c121-4507-8b47-ab81dff216f0)

**Comment by CB987** [comment]
that's weird,  but also they shouldn't have anything from me yet.

**Comment by CB987** [comment]
![Screen Shot 2023-02-20 at 7.41.51 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/f28fec76-7ed8-423f-b3d5-4f613bdfb516)
So far. 
Need to fix background of other dropdown menus (assume we want them all dark letter on white background?)
branding font size.
anything else?

**Comment by CB987** [comment]
Changes requested by Elizabeth yesterday are in progress.

**Comment by CB987** [comment]
![Screen Shot 2023-02-22 at 4.07.17 PM.png](https://images.zenhubusercontent.com/5d379c9d5221e52414fca85c/3513c7cc-3c11-46c5-ad39-aa1f4fbab464)
@erussey this is *configured* ;) with minimal changes to actual code. does this have more the look that you were thinking?

**Comment by CB987** [comment]
(for future reference, changes made using these instructions: https://archivesspace.github.io/tech-docs/customization/theming.html)

**Comment by erussey** [comment]
@CB987 : in the latest deploy, something happened.  It's not looking like the screenshot above.

**Comment by CB987** [comment]
Hmm, i see that the image link is broken. I will look into that, thanks!

**Comment by CB987** [comment]
I traced the issue with the image. The instructions are a little contradictory, and since it was working on my local I didn't dig any deeper. It needs redeploying, but the fix should be in place now (do I need to reach out to Blake again for redeploy, or is it ok until next monday?)
On the page linked above, it says to follow a code example using image_tag, but then in a note it says that rails tag helpers like image_tag won't work "will not be precompiled by the Rails asset pipeline". So it just had to be refactored to use html, not erb. This is good to note for future errors.

**Comment by erussey** [comment]
Just adding the note that the login info is tabbed over to the left instead of flush, which needs to be fixed as well.

**Comment by CB987** [comment]
Increased estimate to 5 because additional work was needed after deploy revealed that there were unforeseen interactions with other plugins only available on the test site, not locally. I had a meeting with Blake from Lyrasis and have a new PR which hopefully will address those issues, but we will not know until they are deployed.

**Comment by rotated8** [comment]
Blocked, @CB987 will reach out to Blake to ensure current approach will work.

**Comment by erussey** [comment]
I am assuming that the blue is there.  I can't see it because it's overridden by #78.
