### ISSUE TITLE
Customize admin footer

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#76]

**Comment by erussey** [comment]
For the scrum team: Would it be helpful to customize the footer on the staff side to add the version number? Or is this just additional work that isn't helpful and we would just rather keep the default footer on the staff side?

Updated comment that I think the ASpace version number is in the staff side footer by default.  If that is the case, we can close ticket and do not need to make any footer changes on the staff side.

**Comment by bwatson78** [comment]
The version of both the Public and Staff Frontend applications are always displayed in the out-of-the-box footer. Its usefulness is debatable, though, since the general structure of plugin incorporation is very unlikely to change without Lyrasis announcing and training on it. What would be useful is something I can't verify is in the applications' code after a couple hours of scouring. Which is whether ArchiveSpace can display the branch/tag of the plugins we ask them to deploy. That could be a useful question to Lyrasis--not a time-sensitive question, so to speak, since we could keep track of what versions are being deployed by Lyrasis by documenting the completed deployments on our own Slack channel.

To be pithy about it, the question is: Is there a mechanism in place that references what versions of our plugins are currently live on a given application?

@erussey If you could reach out to Lyrasis with that question, it would be useful, but not imperative, to hear their answer.

**Comment by bwatson78** [comment]
@erussey Oh, and if you feel that that last comment takes care of the question, I'll leave it to you to close it. I'll leave it open in case my comment above spawns more related questions.

**Comment by erussey** [comment]
I have followed up with Lyrasis and here is their response: 

> We can turn on the ArchivesSpace version in the footer, but there's not much we can do about the plugins version anywhere. That is a good idea though, maybe a good enhancement request for ArchivesSpace to have that show up someplace.   

Looks like we will need to keep track of plug-in versions running in test/prod locally. @rotated8 is there a LTDS process for this already?

**Comment by rotated8** [comment]
@erussey No, we don't have an existing process for this, since this deployment method is unique to ASpace. Internally, we will track plugin versions in our deployment repository.
