### ISSUE TITLE
Explore how to configure an ArchivesSpace export service

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#77]
We would like to set up a public repository in Github that contains exported EAD files, automatically updated nightly from ASpace.  The service should export EAD files from ASpace, create new versions if a file has been updated, and delete any EAD files (and the versions) if the resource has been unpublished since the last update.  I am somewhat agnostic as to whether we implement EAD 2002 or EAD3, though I prefer EAD3 since it is the most current.  

There's several institutions that have set up something similar:
Export service plug-in: https://github.com/hudmol/archivesspace_export_service https://github.com/YaleArchivesSpace/Archives-at-Yale-EAD3 (Yale)
Export service plug-in: https://github.com/RockefellerArchiveCenter/as_export (Rockefeller)

Please explore what we would need to do to set up such a service and estimate the work involved in doing so.  Please also export a finding aid using the EAD exporter that would be used in such a service for resource 5687 (in repository 7) so I can assess if changes also need to be made to the exporter itself.

**Comment by bwatson78** [comment]
Preliminary Findings:
- The Rockefeller code isn't a plugin, but its own application that operates outside of an ArchivesSpace application. It is written all in Python, so customizing it would need the help of Python developers (Zo and Collin). Out of the box, it will always export the record's EAD and METS, and the application will keep track of what has been added, replaced, or removed in its log file. There is no option for EAD3 listed, but could likely be incorporated with our customizations, since ArchivesSpace has a serializer for EAD3 built in.
- Hudmol's ArchivesSpace Export Service was developed for Yale and can be used as a standalone application as well, but also has a plugin operation. The major downside of this code is that it hasn't been updated in 5 years. Although, tricolibs has forked this code May of 2022, but it's not obvious if they're currently using the code at all. It is also not clear if Yale is using this code at the moment, either. 

My next steps are to search the User Group for clues to the ease of install for this plugin.

**Comment by bwatson78** [comment]
The User Group didn't produce much as far as insight. There were a couple of comments of users saying that Hudmol's plugin was producing errors when attempting to upgrade their ArchivesSpace to v3.0.0 Release Candidate. There was a patch that was released for ASpace that seemed to fix that issue.

**Comment by bwatson78** [comment]
Looking at both of the listed options, I would lean towards the Hudmol/Yale plugin/app because it still has configurations written in Ruby and Yale is sporting a Github page with their EAD3s. I will be reaching out to Yale in the User Group (if I can find a good Yale user in the group pretty easily) to ask if they have some tips/recommendations. 

My estimation? 

I see way too many variables that will stop this from being a "one-and-done" install. From the age of the code to the evidence of just a few using this processing in their own instance, I foresee that an installation process that seems like a day may balloon to many. 

I recommend a 13.

But I'd also like @rotated8 to look over my thoughts and chime in before you move forward with this recommendation.

**Comment by erussey** [comment]
@rotated8 @bwatson78 : found another example of this type of service: https://github.com/sciencehistory/export_archivesspace_xml

I also am in touch with the product owner of the above and someone at Rockefeller.  Both willing to talk to us if we want.  Rockefeller might be helpful since they do extensive development on their ASpace and would be able to help us with pros/cons of each approach.  Let me know if you want me to set something up.

**Comment by rotated8** [comment]
The Hudmol plugin additionally requires Java, and it looks like a bunch of the export logic is tied up in compiled Java classes. That's got big maintainability alarms for me, and the age of the repo doesn't help. The Science History setup is nice- it has server setup instructions, and is written in ruby- but it's built to run on Heroku, which we wouldn't do, and puts the files into S3, which isn't what we want. The Rockefeller version is Python, but otherwise appears to function the way we want.

My recommendation is to run the Rockefeller tool on one of our servers.

**Comment by rotated8** [comment]
The work to implement this is something like:

1. Create a GitHub repo to take the EAD files
1. Add a [write-enabled deploy key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/managing-deploy-keys#deploy-keys) for that repo.
1. Identify or create a server with Python 3.4+.
1. Create a user on that server, give them the deploy key.
1. Clone the GitHub repo using the deploy key. This path will be the data directory for the `as_export` configuration.
1. Clone the [as_export](https://github.com/RockefellerArchiveCenter/as_export) repository.
1. Create a `virtualenv`, install `pip` and use it to install the `as_export` requirements.
1. In the `as_export` directory, create `local_settings.cfg` as explained in the README.
1. Setup a `cron` command to run `as_export` on a regular basis.
1. Run `as_export` once explicitly, as the first run will take longer, and to ensure the environment and GitHub setup are working.
