### ISSUE TITLE
Modify Shibboleth settings for prod ASpace staff environment.

### ISSUE THREAD

**Issue by erussey** [emory-libraries/aspace#87]
The current URL for the prod staff side environment is https://emory.lyrasistechnology.org/  .  This needs to be changed to https://emory.lyrasistechnology.org/staff so we can stand up a production PUI instance at the original URL.  The staff environment has a Shibboleth integration that will need to be modified.

This work will need to be coordinated carefully with Blake at Lyrasis since this production environment is in active use and we want to minimize downtime.

**Comment by kbowaterskelly** [comment]
This change is several changes. The metadata for anything, including an existing shibboleth-authenticated application, needs to be exactly the same, down to the byte. Since the url will change, and there may be a UUID or similar that may differ (which I will check) here is the plan.

1. Retrieve new metadata from Lyrasis, compare to existing (us/me). This step may differ according to the information the administrator from Lyrasis provides. Gather rollback information.
2. Authorize new metadata (for /staff) with Shibboleth team (Gerry Hall, OIT). 
3. Move existing instance of AS to new URL during business hours (Lyrasis), then test authentication (Us). Rollback if needed.
4. Authorize old url with new metadata, if needed. (Gerry Hall, OIT)
5. Stand up new production instance (Lyrasis) at the old URL, then test authentication (Us).

I am hopeful to have this take place by Wed 3/1 but this will take place after the sprint closing meeting. This change requires coordination across us, OIT, and Lyrasis. Downtime in this process should be limited to 5-15 minutes. We will maintain the ability to rollback any changes that would negatively impact service availability.

**Comment by kbowaterskelly** [comment]
Currently coordinating this between Lyrasis and OIT. With luck the change will be finalized tomorrow, if not, might be a few more business days and a scheduled maintenance window of a few hours. The PUI will be stood up at the same time as this change is finalized.

**Comment by lovinscari** [comment]
@kbowaterskelly - Please update the ticket with who you have been working with at Lyrasis and OIT in trying to coordinate this. I believe we just need to get a block of time when everyone is available and I want to see if I can help coordinate this since this is a high priority ticket submitted 16 days ago.

**Comment by AGCooper** [comment]
In touch with Gerry Hall from OIT. Kaeln to schedule a meeting with Lyrasis and him to try the switch over again and troubleshoot. Gerry indicated he should be available 03/02 or 03/03.

**Comment by erussey** [comment]
I would very much appreciate a window on either 3/3 or after 5pm today.  I need to be able to give as much lead time as I can to the archivists since this involves downtime on a production system and a URL change.

**Comment by kbowaterskelly** [comment]
We're not able to do that because Shibboleth is not supported after hours. I have the change scheduled for 2-3pm today. If this is too soon, I will be forced to reschedule and we will hope to get a different window tomorrow.
________________________________
From: Elizabeth Russey Roke ***@***.***>
Sent: Thursday, March 2, 2023 11:00 AM
To: emory-libraries/aspace ***@***.***>
Cc: Bowater-Skelly, Kaeln Joseph ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [emory-libraries/aspace] Modify Shibboleth settings for prod ASpace staff environment. (Issue #87)


I would very much appreciate a window on either 3/3 or after 5pm today. I need to be able to give as much lead time as I can to the archivists since this involves downtime on a production system and a URL change.

**Comment by AGCooper** [comment]
Application moved and login is functional.
